[package]
authors = ["ruin"]
name = "sabi"
version = "0.1.0"

[features]
with-opengl = ["glium"]
with-rustbox = ["rustbox"]
with-tcod = []

[dependencies]
rand = "0.3.15"
tcod = "0.11.0"
ears = "0.4.0"
euclid = "0.11.0"
bitflags = "0.8.0"
slog = "1.2"
slog-stream = "1.2"
env_logger = "0.3"
chrono = "0.3.0"
backtrace = "0.3"
uuid = { version = "0.4.0", features = ["serde", "v4"]}

glium = { version = "0.16.0", optional = true }
rustbox = { version = "0.9.0", optional = true }
