[package]
authors = ["ruin"]
name = "sabi"
version = "0.1.0"

[features]
with-opengl = ["glium"]
with-rustbox = ["rustbox"]
with-tcod = []

[dependencies]
tcod = "0.11.0"
ears = "0.4.0"
euclid = "0.11.0"
bitflags = "0.8.0"
log = "0.3"
env_logger = "0.3"

glium = { version = "0.16.0", optional = true }
rustbox = { version = "0.9.0", optional = true }
